// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlnbgbmjoetklynekmav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sbmJnYm1qb2V0a2x5bmVrbWF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMTkwMjMsImV4cCI6MjA3Mzg5NTAyM30.jrA7gHBZ_w1yUb0AMM0DiVJFy660qV-jsoDWEQqV4Gc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});